name: Build android

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  build:
    runs-on: self-hosted
    
    steps:
    - uses: actions/checkout@v2
    
    - name: clean
      run: ./gradlew clean
      
    - name: assemble debug
      run: ./gradlew assembleDebug
      
    - uses: actions/upload-artifact@v3
      with:
        name: app-debug.apk
        path: ./app/build/outputs/apk/debug/app-debug.apk
