name: Build android

on: [ push, pull_request ]

jobs:
  build:
    runs-on: self-hosted
    
    steps:
    - uses: actions/checkout@v2
    
    - name: clean
      run: ./gradlew clean
      
    - name: assemble debug
      run: ./gradlew assembleDebug
